name: Update Javadoc
on:
    push:
        tags:
            - '*'
    workflow_dispatch: { }
permissions:
    contents: write
    pages: write


jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
            -   name: Setup system dependencies
                run: |
                    sudo apt-get install python3-bs4
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3
            -   name: Setup Java 21
                uses: actions/setup-java@v3
                with:
                    distribution: temurin
                    java-version: 21
            -   name: Generate JavaDoc
                run: |
                    ./gradlew dokkaHtml --stacktrace
            -   name: Upload JavaDoc
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./build/dokka/html
